import streamlit as st
import google.generativeai as genai
from docx import Document
from io import BytesIO

# --- PAGE SETUP ---
st.set_page_config(page_title="Pro Agency Writer 2.0", page_icon="🚀")
st.title("🚀 Pro Agency Content Writer (Gemini 2.0)")
st.write("Ab hum Latest Gemini 2.0 Flash use kar rahe hain for 1500+ words SEO content.")

# --- API KEY SETUP ---
if "GEMINI_API_KEY" in st.secrets:
    api_key = st.secrets["GEMINI_API_KEY"]
else:
    api_key = st.sidebar.text_input("Enter Gemini API Key:", type="password")

if not api_key:
    st.info("💡 Sidebar mein API Key daalein ya Streamlit Secrets set karein.")
    st.stop()

# --- AI SETUP (GEMINI 2.0) ---
try:
    genai.configure(api_key=api_key)
    # Updated to Gemini 2.0 Flash
    model = genai.GenerativeModel('gemini-2.0-flash')
except Exception as e:
    st.error(f"Setup Error: {e}")

# --- INTERFACE ---
topic = st.text_input("📝 Article ka Topic ya Keyword daaliye:")

if st.button("Generate Masterpiece 🚀"):
    if not topic:
        st.warning("⚠️ Topic toh likhiye!")
    else:
        # Prompt for 1500 words, SEO, and Human Tone
        prompt = f"""
        Role: Expert SEO Content Writer & Strategist.
        Task: Write a comprehensive, 1500-word article on: '{topic}'.
        
        Strict Instructions:
        1. Length: Must be around 1500 words (Deep dive).
        2. Tone: 100% Natural Human tone, conversational, engaging. NO AI-ish robotic words.
        3. SEO: Include H1, H2, and H3 tags. Use bullet points and a Table of Contents.
        4. Structure: Intro, multiple detailed sections, Case studies/Examples if possible, and a Conclusion.
        5. Keywords: Use keywords naturally throughout the text.
        """
        
        with st.spinner("✨ Gemini 2.0 dimaag laga raha hai... Ye 1500 words ka article hai, toh 30-60 seconds lag sakte hain..."):
            try:
                response = model.generate_content(prompt)
                article_text = response.text
                
                st.success("🎉 Article Ready! (Generated by Gemini 2.0)")
                
                # Copy Box
                st.text_area("Yahan se copy karein:", value=article_text, height=450)
                
                # Word File Creator
                doc = Document()
                doc.add_heading(topic, 0)
                doc.add_paragraph(article_text)
                bio = BytesIO()
                doc.save(bio)
                
                st.download_button(
                    label="📄 Download Word File",
                    data=bio.getvalue(),
                    file_name=f"{topic.replace(' ', '_')}_2.0.docx",
                    mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
                )
            except Exception as e:
                st.error(f"Opps! Technical Error: {e}")
